### ISSUE TITLE
Map is not defined

### ISSUE THREAD

**Issue by meodai** [studioijeoma/ijeoma.js#1]
Uncaught ReferenceError: map is not defined. As soon a Tween is used that takes an array as min and max argument: http://ekeneijeoma.github.io/ijeoma.js/examples/Tween.html

**Comment by studioijeoma** [comment]
I'm in the middle of adding support of array interpolation so something may be unstable. In the meantime just download the stable release and run the examples locally.

**Comment by studioijeoma** [comment]
I just fixed this issue but the build is still unstable as I'm adding array interpolation.

**Comment by meodai** [comment]
oh for some reason I was not on the master branch, I'm sorry! Thank you

**Comment by studioijeoma** [comment]
the master branch hasnt been synced in a while. just download the first release here https://github.com/ekeneijeoma/ijeoma.js/releases. this will all be updated soon.

**Comment by meodai** [comment]
I will, thank you for your help
