### ISSUE TITLE
B&W button on the gradient example seems to have counterintuitive effect

### ISSUE THREAD

**Issue by timseverien** [studioijeoma/ijeoma.js#2]
To me, the black and white button on the [gradient examle](http://ekeneijeoma.github.io/ijeoma.js/examples/gradients.html) should have effect on the entire gradient. Instead, only one colorStop of the gradient is set to b&w. This could be a little bug or just my perception so I’ll leave this in the middle.

**Comment by studioijeoma** [comment]
It's not a bug it's an effect. The gradient animates from left to right and when you change the color mode it transitions from last color value to the next black and white value. Otherwise it would be a hard transition.
